# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: reidransom
email: reid@reidransom.com
description: >- # this means to ignore newlines until "baseurl:"
  I’m Reid Ransom — a full-stack engineer, founder of r2ware, and technology
  leader with experience building and scaling products for global companies
  and mission-driven organizations. I’ve led engineering at Premiere Digital
  Services and Defy Ventures, and my work has been recognized by
  Inc., Nokia + Wired, and Mark Zuckerberg. Beyond work, I’m a husband and
  father, a Boston Marathon finisher, and proudly sober since 2022.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://reidransom.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: reidransom
github_username:  reidransom

# Build settings
theme: hitchens-theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

favicon_svg: /assets/ico/favicon.svg

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude:
  - README.md
  - WARP.md

hide_credits: true
hide_search: true
excerpt_length: 30
comentario_script: http://comments.rpdev.lan:5050/comentario.js
